Fix Compilation Error in React Native 0.47.0
createJSModules was removedin React Native 0.47.0 and results in the attached Build Error.
removing `@Override` fixes build (didn't remove function because I don't know if it should be kept for downard compatability?)

```
node_modules/react-native-image-crop-picker/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerPackage.java:18: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: /home/mmb/git/climbz2/climbz-reactnative/node_modules/react-native-image-crop-picker/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
:react-native-image-crop-picker:compileReleaseJavaWithJavac FAILED
```